---
title: "20230411_puncta_circularity"
output: html_document
date: "2023-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
#loaded RStudioAPI to use for selecting working directory
if("rstudioapi" %in% rownames(installed.packages()) == FALSE) 
{install.packages("rstudioapi")}
library(rstudioapi)
if("xlsx" %in% rownames(installed.packages()) == FALSE) 
{install.packages("xlsx")}
library(xlsx)
if("reshape" %in% rownames(installed.packages()) == FALSE) 
{install.packages("reshape")}
library(reshape)
if("data.table" %in% rownames(installed.packages()) == FALSE) 
{install.packages("data.table")}
library(data.table)
if("stringi" %in% rownames(installed.packages()) == FALSE) 
{install.packages("stringi")}
library(stringi)
if("tidyverse" %in% rownames(installed.packages()) == FALSE) 
{install.packages("tidyverse")}
library(tidyverse)
library(ggplot2)

```


```{r load data}
dataFile <- selectDirectory(
  caption = "Select Directory",
  label = "Select",
  path = getActiveProject()
)
setwd(dataFile)


allFiles <- dir()
imageIndices <- 0

for (i in 1:length(allFiles)){
  currentFile <- allFiles[i]
    imageIndices <- append(imageIndices, i)
}


for(i in 2:length(imageIndices)){
  if(i == 2){
    imageFiles <- allFiles[imageIndices[i]]
  }
  if(i != 2){
    imageFiles <- append(imageFiles, allFiles[imageIndices[i]])
  }
}

#imageFiles is all folders 
for(i in 1:length(imageFiles)) {
  currentFile <- imageFiles[i]
  pathOutput <- paste(currentFile, 'Output', sep = "/")
  if (i == 1) {
    fileList <- dir(pathOutput)
    for(j in 1:length(fileList)){
      fileList[j] <- paste(pathOutput, fileList[j], sep = "/")
    }
  }
  if (i != 1) {
    newFiles <- dir(pathOutput)
    for(j in 1:length(newFiles)){
      newFiles[j] <- paste(pathOutput, newFiles[j], sep = "/")
    }
    fileList <- append(fileList, newFiles)
  }
}

#redFiles and greenFiles stores the names of images
redFiles <- str_subset(fileList, pattern = 'redResults')
greenFiles <- str_subset(fileList, pattern = 'greenResults')
colocFiles <- str_subset(fileList, pattern = 'colocResults')
redDataIn <- lapply(redFiles, read.csv)
greenDataIn <- lapply(greenFiles, read.csv)
colocDataIn <- lapply(colocFiles, read.csv)

```

```{r get circularity}
#gives the average circularity for each image
redCircVector <- c(mode = "numeric", length = length(redDataIn))

for(i in 1:length(redDataIn)) {
  currentData <- redDataIn[[i]]
  redCircVector[i] <- mean(currentData$Circ.)
}

greenCircVector <- c("numeric", length(greenDataIn))

for(i in 1:length(greenDataIn)) {
  currentData <- greenDataIn[[i]]
  greenCircVector[i] <- mean(currentData$Circ.)
}

#it seems to make vectors character type even if I say numeric
redCircVector <- as.numeric(redCircVector)
greenCircVector <- as.numeric(greenCircVector)


print(paste("mean circularity for red ", mean(redCircVector)))
print(paste("sd circularity for red ", sd(redCircVector)))
print(paste("mean circularity for green ", mean(greenCircVector)))
print(paste("sd circularity for green ", sd(greenCircVector)))
```





