---
title: "20240316_check_accuracy"
output: html_document
date: "2024-03-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
#loaded RStudioAPI to use for selecting working directory
if("rstudioapi" %in% rownames(installed.packages()) == FALSE) 
{install.packages("rstudioapi")}
library(rstudioapi)
if("xlsx" %in% rownames(installed.packages()) == FALSE) 
{install.packages("xlsx")}
library(xlsx)
if("reshape" %in% rownames(installed.packages()) == FALSE) 
{install.packages("reshape")}
library(reshape)
if("data.table" %in% rownames(installed.packages()) == FALSE) 
{install.packages("data.table")}
library(data.table)
if("stringi" %in% rownames(installed.packages()) == FALSE) 
{install.packages("stringi")}
library(stringi)
if("tidyverse" %in% rownames(installed.packages()) == FALSE) 
{install.packages("tidyverse")}
library(tidyverse)
library(ggplot2)
library(DescTools)

```


```{r load data}
dataFile <- selectDirectory(
  caption = "Select Directory",
  label = "Select",
  path = getActiveProject()
)
setwd(dataFile)


allFiles <- dir()
imageIndices <- 0

for (i in 1:length(allFiles)){
  currentFile <- allFiles[i]
    imageIndices <- append(imageIndices, i)
}


for(i in 2:length(imageIndices)){
  if(i == 2){
    imageFiles <- allFiles[imageIndices[i]]
  }
  if(i != 2){
    imageFiles <- append(imageFiles, allFiles[imageIndices[i]])
  }
}

#imageFiles is all folders 
for(i in 1:length(imageFiles)) {
  currentFile <- imageFiles[i]
  pathOutput <- paste(currentFile, 'Output', sep = "/")
  if (i == 1) {
    fileList <- dir(pathOutput)
    for(j in 1:length(fileList)){
      fileList[j] <- paste(pathOutput, fileList[j], sep = "/")
    }
  }
  if (i != 1) {
    newFiles <- dir(pathOutput)
    for(j in 1:length(newFiles)){
      newFiles[j] <- paste(pathOutput, newFiles[j], sep = "/")
    }
    fileList <- append(fileList, newFiles)
  }
}

#redFiles and greenFiles stores the names of images
redFiles <- str_subset(fileList, pattern = 'redResults')
greenFiles <- str_subset(fileList, pattern = 'greenResults')
colocFiles <- str_subset(fileList, pattern = 'colocResults')

#check that all the files are not empty

emptyRedList <- c()
emptyGreenList <- c()
emptyColocList <- c()

fixedRedFiles <- c()

for(i in 1:length(redFiles)){
  currentSize <- file.size(redFiles[i])
  if(currentSize <= 4){
    emptyRedList <- c(emptyRedList, redFiles[i])
  }
  if(currentSize > 4){
    fixedRedFiles <- c(fixedRedFiles, redFiles[i])
  }
}

fixedGreenFiles <- c()

for(i in 1:length(greenFiles)){
  currentSize <- file.size(greenFiles[i])
  if(currentSize <= 4){
    emptyGreenList <- c(emptyGreenList, greenFiles[i])
  }
  if(currentSize > 4){
    fixedGreenFiles <- c(fixedGreenFiles, greenFiles[i])
  }
}

fixedColocFiles <- c()

for(i in 1:length(colocFiles)){
  currentSize <- file.size(colocFiles[i])
  if(currentSize <= 4){
    emptyColocList <- c(emptyColocList, colocFiles[i])
  }
  if(currentSize > 4){
    fixedColocFiles <- c(fixedColocFiles, colocFiles[i])
  }
}

#"D:/Eroglu_lab/images/sim_sparse_ilastik_1/group/Output/KO_Pair1_L2R1_1-3_sim_0_00_colocResults_0.csv"

redDataIn <- lapply(fixedRedFiles, read.csv)
greenDataIn <- lapply(fixedGreenFiles, read.csv)
colocDataIn <- lapply(fixedColocFiles, read.csv)

```


```{r load in ground truth}
#read in ground truth data
true_red <- read.delim("simulated_data/red_truth.txt", header = FALSE)
colnames(true_red) <- c("coord_string")
true_red$x <- -1
true_red$y <- -1

true_green <- read.delim("simulated_data/green_truth.txt", header = FALSE)
colnames(true_green) <- c("coord_string")
true_green$x <- -1
true_green$y <- -1

for(i in 1:length(true_red$coord_string)){
  currentString <- true_red$coord_string[i] 
  true_red$x[i] <- as.integer(strsplit(currentString, ",")[[1]][1])
  true_red$y[i] <- as.integer(strsplit(currentString, ",")[[1]][2])
}

for(i in 1:length(true_green$coord_string)){
  currentString <- true_green$coord_string[i] 
  true_green$x[i] <- as.integer(strsplit(currentString, ",")[[1]][1])
  true_green$y[i] <- as.integer(strsplit(currentString, ",")[[1]][2])
}

#intersect red and green puncta coordinates to see true colocs
true_colocs <- filter(true_red, coord_string %in% true_green$coord_string)

#initailize output data frame
output_df <- data.frame(fixedColocFiles)
colnames(output_df) <- c("image")
output_df$true_pos_count <- 0
output_df$false_pos_count <- 0
output_df$false_neg_count <- 0
output_df$true_neg_count <- 0

```



```{r calculate recall}

#recall is true positive / (true positve + false negative)
#recall is the same as true positive rate

#for each image
for(m in 1:length(colocDataIn)){
  
  currentData = colocDataIn[[m]]
  
  #for each location in the ground truth
  for(ii in 1:length(true_colocs$coord_string)){
    currentTrueX <- true_colocs$x[ii]
    currentTrueY <- true_colocs$y[ii]
    
    #print(currentTrueX)
    #print(currentTrueY)
    
    #set match_found to false and then set it to true if any of the puncta overlap the truth
    match_found <- FALSE
    
    #for each puncta in the image
    for(j in 1:length(currentData$colocX)){
      currentX <- currentData$colocX[j]
      currentY <- currentData$colocY[j]
      
      if(currentX > (currentTrueX - 5) && currentX < (currentTrueX + 5)){
        if(currentY > (currentTrueY - 5) && currentY < (currentTrueY + 5)){
          match_found <- TRUE
        }
      }
    }
    
    if(match_found == TRUE){
      #print("true pos")
      output_df$true_pos_count[m] <- output_df$true_pos_count[m] + 1
    }
    if(match_found == FALSE){
      #print("false neg")
      output_df$false_neg_count[m] <- output_df$false_neg_count[m] + 1
    }
  }
}

#add in empty images
empty_colocs_df <- data.frame(emptyColocList)

if(length(emptyColocList) > 0){

  colnames(empty_colocs_df) <- c("image")
  empty_colocs_df$true_pos_count <- 0
  empty_colocs_df$false_pos_count <- 0
  empty_colocs_df$false_neg_count <- length(true_colocs$coord_string)
  empty_colocs_df$true_neg_count <- 0
  
  output_df <- rbind(output_df, empty_colocs_df)

}

output_df$recall <- output_df$true_pos_count/(output_df$true_pos_count+output_df$false_neg_count)

# change NaN values to zero
output_df$recall[which(is.na(output_df$recall))] <- 0

```


```{r calculate precision}

#precision is true positive / (true positive + false positive)

#for each image
for(m in 1:length(colocDataIn)){
  
  currentData = colocDataIn[[m]]
  
  #for each puncta in the image
  for(j in 1:length(currentData$colocX)){
    currentX <- currentData$colocX[j]
    currentY <- currentData$colocY[j]
    
    #set match_found to false and then set it to true if any of the puncta overlap the truth
    match_found <- FALSE
    
    #for each location in the ground truth
    for(ii in 1:length(true_colocs$coord_string)){
      currentTrueX <- true_colocs$x[ii]
      currentTrueY <- true_colocs$y[ii]
      
    #print(currentTrueX)
    #print(currentTrueY)
      
      if(currentX > (currentTrueX - 5) && currentX < (currentTrueX + 5)){
        if(currentY > (currentTrueY - 5) && currentY < (currentTrueY + 5)){
          match_found <- TRUE
        }
      }
    }
    
    if(match_found == TRUE){
      #true positives already counted
      #print("true pos")
      #output_df$true_pos_count[m] <- output_df$true_pos_count[m] + 1
    }
    #if none of the true locations match this punctas location
    if(match_found == FALSE){
      #print("false neg")
      output_df$false_pos_count[m] <- output_df$false_pos_count[m] + 1
    }
  }
}

output_df$precision <- output_df$true_pos_count/(output_df$true_pos_count+output_df$false_pos_count)

# change NaN values to zero
output_df$precision[which(is.na(output_df$precision))] <- 0


```


```{r add metadata for plots}


#initialize columns
output_df$noise_level <- "unknown"

#lable data with noise level
output_df[which(grepl("0_00", output_df$image)),]$noise_level <- "0.00"
output_df[which(grepl("0_25", output_df$image)),]$noise_level <- "0.25"
output_df[which(grepl("0_50", output_df$image)),]$noise_level <- "0.50"
output_df[which(grepl("0_75", output_df$image)),]$noise_level <- "0.75"
output_df[which(grepl("1_00", output_df$image)),]$noise_level <- "1.00"

output_df$noise_level <- factor(output_df$noise_level, levels = c("0.00", "0.25", "0.50", "0.75", "1.00"))

output_df$image_id <- seq.int(nrow(output_df))

#write.csv(output_df, "output_df_ilastik.csv")

```


```{r plot read from file}

output_df <- read.csv("output_df_ilastik.csv", header = TRUE)

recall_means <- summarize(group_by(output_df, noise_level), mean(recall)) 

colnames(recall_means) <- c("noise_level", "recall")

recall_means$sd <- summarize(group_by(output_df, noise_level), sd(recall))$`sd(recall)`

recall_means$sem <- recall_means$sd/sqrt(length(output_df$recall))

ggplot(data = recall_means, aes(x = noise_level, y = recall)) + geom_line() + geom_errorbar(aes(ymin=recall-sem, ymax=recall+sem), width=.1) + ylim(0, 1)

precision_means <- summarize(group_by(output_df, noise_level), mean(precision)) 

colnames(precision_means) <- c("noise_level", "precision")

precision_means$sd <- summarize(group_by(output_df, noise_level), sd(precision))$`sd(precision)`

precision_means$sem <- precision_means$sd/sqrt(length(output_df$precision))

ggplot(data = precision_means, aes(x = noise_level, y = precision)) + geom_line() + geom_errorbar(aes(ymin=precision-sem, ymax=precision+sem), width=.1) + ylim(0, 1)


```


```{r make faceted plots}

manual_data <- read.csv("output_df_manual.csv")
manual_data$analysis_type <- "manual"
ilastik_data <- read.csv("output_df_ilastik.csv")
ilastik_data$analysis_type <- "ilastik"
synquant_data <- read.csv("output_df_synquant_10_12.csv")
synquant_data$analysis_type <- "synquant"
#synquant_10_8_data <- read.csv("output_df_synquant_10_8.csv")
#synquant_10_8_data$analysis_type <- "synquant_10_8"

combined_data <- rbind(manual_data, ilastik_data, synquant_data)

recall_means <- summarize(group_by(combined_data, noise_level, analysis_type), mean(recall)) 

colnames(recall_means) <- c("noise_level", "analysis_type", "recall")

recall_means$sd <- summarize(group_by(combined_data, noise_level, analysis_type), sd(recall))$`sd(recall)`

recall_means$sem <- recall_means$sd/sqrt(length(combined_data$recall))

#ggplot(data = recall_means, aes(x = noise_level, y = recall, color = analysis_type)) + geom_line() + geom_errorbar(aes(ymin=recall-sem, ymax=recall+sem), width=.1) + ylim(0, 1) +scale_color_ordinal(name = "Thresholding Method") + xlab("noise level") + ylab(expression(paste("recall  ", frac("TP", "TP + FP"))))

ggplot(data = recall_means, aes(x = noise_level, y = recall, color = analysis_type)) + geom_line() + geom_errorbar(aes(ymin=recall-sem, ymax=recall+sem), width=.1) + ylim(0, 1) +scale_color_ordinal(name = "Thresholding Method") + xlab("noise level") + ylab("recall")

#ggsave("C:/Users/savag/Duke Research Team Dropbox/Justin Savage/Team_Syn_Bot/20230103_figures/figure_0_simulated_data/synbot_recall.pdf", width = 5, height = 2.75)

#ggplot(data = recall_means, aes(x = noise_level, y = recall)) + geom_line() + geom_errorbar(aes(ymin=recall-sem, ymax=recall+sem), width=.1) + ylim(0, 1) + facet_grid(cols = vars(analysis_type))

#ggplot(data = recall_means, aes(x = analysis_type, y = recall)) + geom_point(size = 1) + geom_errorbar(aes(ymin=recall-sem, ymax=recall+sem), width=.1) + ylim(0, 1) + facet_grid(cols = vars(noise_level))

precision_means <- summarize(group_by(combined_data, noise_level, analysis_type), mean(precision)) 

colnames(precision_means) <- c("noise_level", "analysis_type", "precision")

precision_means$sd <- summarize(group_by(combined_data, noise_level, analysis_type), sd(precision))$`sd(precision)`

precision_means$sem <- precision_means$sd/sqrt(length(combined_data$precision))

ggplot(data = precision_means, aes(x = noise_level, y = precision, color = analysis_type)) + geom_line() + geom_errorbar(aes(ymin=precision-sem, ymax=precision+sem), width=.1) + ylim(0, 1) +scale_color_ordinal(name = "Thresholding Method") + xlab("noise level") + ylab("precision")

#ggsave("C:/Users/savag/Duke Research Team Dropbox/Justin Savage/Team_Syn_Bot/20230103_figures/figure_0_simulated_data/synbot_precision.pdf", width = 5, height = 2.75)

#ggplot(data = precision_means, aes(x = noise_level, y = precision)) + geom_line() + geom_errorbar(aes(ymin=precision-sem, ymax=precision+sem), width=.1) + ylim(0, 1) + facet_grid(cols = vars(analysis_type)) 

#ggplot(data = precision_means, aes(x = analysis_type, y = precision)) + geom_point(size = 1) + geom_errorbar(aes(ymin=precision-sem, ymax=precision+sem), width=.1) + ylim(0, 1) + facet_grid(cols = vars(noise_level)) 

```



```{r stats on recall}

print("ANOVA of recall by analysis type")
analysis_anova <- aov(recall~analysis_type, data = combined_data)
summary(analysis_anova)

analysis_tukey <- TukeyHSD(analysis_anova)
analysis_tukey

#make noise level a factor
combined_data$noise_level <- as.factor(combined_data$noise_level)

print("ANOVA of recall by analysis type and noise level")
analysis_anova <- aov(recall~analysis_type+noise_level, data = combined_data)
summary(analysis_anova)

analysis_tukey <- TukeyHSD(analysis_anova)
analysis_tukey

#Try ANOVA between methods at each noise level
noise_0_00_data <- filter(combined_data, noise_level == 0.00)
noise_0_25_data <- filter(combined_data, noise_level == 0.25)
noise_0_50_data <- filter(combined_data, noise_level == 0.50)
noise_0_75_data <- filter(combined_data, noise_level == 0.75)
noise_1_00_data <- filter(combined_data, noise_level == 1.00)


noise_0_00_anova <- aov(recall~analysis_type, data = noise_0_00_data)
summary(noise_0_00_anova)

noise_0_00_anova_tukey <- TukeyHSD(noise_0_00_anova)
noise_0_00_anova_tukey

noise_0_25_anova <- aov(recall~analysis_type, data = noise_0_25_data)
summary(noise_0_25_anova)

noise_0_25_anova_tukey <- TukeyHSD(noise_0_25_anova)
noise_0_25_anova_tukey

noise_0_50_anova <- aov(recall~analysis_type, data = noise_0_50_data)
summary(noise_0_50_anova)

noise_0_50_anova_tukey <- TukeyHSD(noise_0_50_anova)
noise_0_50_anova_tukey

noise_0_75_anova <- aov(recall~analysis_type, data = noise_0_75_data)
summary(noise_0_75_anova)

noise_0_75_anova_tukey <- TukeyHSD(noise_0_75_anova)
noise_0_75_anova_tukey

noise_1_00_anova <- aov(recall~analysis_type, data = noise_1_00_data)
summary(noise_0_75_anova)

noise_1_00_anova_tukey <- TukeyHSD(noise_1_00_anova)
noise_1_00_anova_tukey
```


```{r stats on precision}

print("ANOVA of precision by analysis type")
analysis_anova <- aov(precision~analysis_type, data = combined_data)
summary(analysis_anova)

analysis_tukey <- TukeyHSD(analysis_anova)
analysis_tukey

#make noise level a factor
combined_data$noise_level <- as.factor(combined_data$noise_level)

print("ANOVA of precision by analysis type and noise level")
analysis_anova <- aov(precision~analysis_type+noise_level, data = combined_data)
summary(analysis_anova)

analysis_tukey <- TukeyHSD(analysis_anova)
analysis_tukey

#Try ANOVA between methods at each noise level
noise_0_00_data <- filter(combined_data, noise_level == 0.00)
noise_0_25_data <- filter(combined_data, noise_level == 0.25)
noise_0_50_data <- filter(combined_data, noise_level == 0.50)
noise_0_75_data <- filter(combined_data, noise_level == 0.75)
noise_1_00_data <- filter(combined_data, noise_level == 1.00)


noise_0_00_anova <- aov(precision~analysis_type, data = noise_0_00_data)
summary(noise_0_00_anova)

noise_0_00_anova_tukey <- TukeyHSD(noise_0_00_anova)
noise_0_00_anova_tukey

noise_0_25_anova <- aov(precision~analysis_type, data = noise_0_25_data)
summary(noise_0_25_anova)

noise_0_25_anova_tukey <- TukeyHSD(noise_0_25_anova)
noise_0_25_anova_tukey

noise_0_50_anova <- aov(precision~analysis_type, data = noise_0_50_data)
summary(noise_0_50_anova)

noise_0_50_anova_tukey <- TukeyHSD(noise_0_50_anova)
noise_0_50_anova_tukey

noise_0_75_anova <- aov(precision~analysis_type, data = noise_0_75_data)
summary(noise_0_75_anova)

noise_0_75_anova_tukey <- TukeyHSD(noise_0_75_anova)
noise_0_75_anova_tukey

noise_1_00_anova <- aov(precision~analysis_type, data = noise_1_00_data)
summary(noise_0_75_anova)

noise_1_00_anova_tukey <- TukeyHSD(noise_1_00_anova)
noise_1_00_anova_tukey
```


