---
title: "20240228_chrdl1_data_plots"
output: html_document
date: "2024-02-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(tidyverse)
library(ggplot2)
library(agricolae)
library(ggsignif)
library(multcomp)
library(nlme)
```


```{r load data}

#manual_synbot_data <- read.csv("a2d1_invivo_data/20230119_juan_manual_cleaned.csv")
#ilastik_data <- read.csv("a2d1_invivo_data/20230125_2_ilastik.csv")

manual_synbot_data <- read.csv("chrdl1_ko_data/chrdl1_ko_manual.csv")
ilastik_data <- read.csv("chrdl1_ko_data/chrdl1_ko_manual.csv")
puncta_analyzer_data <- read.csv("chrdl1_ko_data/chrdl1_ko_manual.csv")
synquant_data <- read.csv("chrdl2_ko_synquant_5_12.csv")
#SynQuant params:
# zscore_thres=10
# MinSize=10
# MaxSize=100
# minFill=0.5
# maxWHRatio=4
# zAxisMultiplier=1
# noiseStd=12


#fix weird column names
colnames(manual_synbot_data) <- colnames(ilastik_data)
colnames(puncta_analyzer_data) <- colnames(ilastik_data)
colnames(synquant_data) <- colnames(ilastik_data)

#label data with the analysis type used
manual_synbot_data$analysis_type <- "manual_synbot"
ilastik_data$analysis_type <- "ilastik"
puncta_analyzer_data$analysis_type <- "puncta_analyzer"
synquant_data$analysis_type <- "synquant"

#make analysis_type a factor so that it always plots in puncta_analyzer, manual, ilastik order
manual_synbot_data$analysis_type <- factor(manual_synbot_data$analysis_type, levels = c("puncta_analyzer", "manual_synbot", "ilastik", "synquant"))

```

```{r add sample metadata in loop}

dfList <- list(manual_synbot_data, ilastik_data, puncta_analyzer_data, synquant_data)

for(i in 1:length(dfList)){
  #initialize columns
  dfList[[i]]$condition <- "unknown"
  dfList[[i]]$animal <- "unknown"
  dfList[[i]]$side <- "unknown"
  
  dfList[[i]][which(grepl("6-4-7", dfList[[i]]$Image)),]$animal <- "6-4-7"
  dfList[[i]][which(grepl("3-7-3", dfList[[i]]$Image)),]$animal <- "3-7-3"
  dfList[[i]][which(grepl("4-6-1", dfList[[i]]$Image)),]$animal <- "4-6-1"
  dfList[[i]][which(grepl("8-5-5", dfList[[i]]$Image)),]$animal <- "8-5-5"
  
  dfList[[i]][which(grepl("6-4-7", dfList[[i]]$Image)),]$condition <- "WT_sham"
  dfList[[i]][which(grepl("3-7-3", dfList[[i]]$Image)),]$condition <- "WT_sham"
  dfList[[i]][which(grepl("4-6-1", dfList[[i]]$Image)),]$condition <- "WT_sham"
  dfList[[i]][which(grepl("8-5-5", dfList[[i]]$Image)),]$condition <- "WT_sham"
  
  dfList[[i]][which(grepl("3-3-2", dfList[[i]]$Image)),]$animal <- "3-3-2"
  dfList[[i]][which(grepl("3-3-5", dfList[[i]]$Image)),]$animal <- "3-3-5"
  dfList[[i]][which(grepl("6-4-8", dfList[[i]]$Image)),]$animal <- "6-4-8"
  dfList[[i]][which(grepl("4-6-2", dfList[[i]]$Image)),]$animal <- "4-6-2"
  dfList[[i]][which(grepl("8-5-7", dfList[[i]]$Image)),]$animal <- "8-5-7"
  
  dfList[[i]][which(grepl("3-3-2", dfList[[i]]$Image)),]$condition <- "WT_pts"
  dfList[[i]][which(grepl("3-3-5", dfList[[i]]$Image)),]$condition <- "WT_pts"
  dfList[[i]][which(grepl("6-4-8", dfList[[i]]$Image)),]$condition <- "WT_pts"
  dfList[[i]][which(grepl("4-6-2", dfList[[i]]$Image)),]$condition <- "WT_pts"
  dfList[[i]][which(grepl("8-5-7", dfList[[i]]$Image)),]$condition <- "WT_pts"
  
  dfList[[i]][which(grepl("3-3-1", dfList[[i]]$Image)),]$animal <- "3-3-1"
  dfList[[i]][which(grepl("3-3-3", dfList[[i]]$Image)),]$animal <- "3-3-3"
  dfList[[i]][which(grepl("6-4-2", dfList[[i]]$Image)),]$animal <- "6-4-2"
  dfList[[i]][which(grepl("8-5-4", dfList[[i]]$Image)),]$animal <- "8-5-4"
  
  dfList[[i]][which(grepl("3-3-1", dfList[[i]]$Image)),]$condition <- "KO_sham"
  dfList[[i]][which(grepl("3-3-3", dfList[[i]]$Image)),]$condition <- "KO_sham"
  dfList[[i]][which(grepl("6-4-2", dfList[[i]]$Image)),]$condition <- "KO_sham"
  dfList[[i]][which(grepl("371", dfList[[i]]$Image)),]$condition <- "KO_sham"
  dfList[[i]][which(grepl("8-5-4", dfList[[i]]$Image)),]$condition <- "KO_sham"
  
  dfList[[i]][which(grepl("6-4-6", dfList[[i]]$Image)),]$animal <- "6-4-6"
  dfList[[i]][which(grepl("4-6-3", dfList[[i]]$Image)),]$animal <- "4-6-3"
  dfList[[i]][which(grepl("4-6-4", dfList[[i]]$Image)),]$animal <- "4-6-4"
  dfList[[i]][which(grepl("371", dfList[[i]]$Image)),]$animal <- "3-7-1"
  dfList[[i]][which(grepl("8-5-6", dfList[[i]]$Image)),]$animal <- "8-5-6"
  
  dfList[[i]][which(grepl("6-4-6", dfList[[i]]$Image)),]$condition <- "KO_pts"
  dfList[[i]][which(grepl("4-6-3", dfList[[i]]$Image)),]$condition <- "KO_pts"
  dfList[[i]][which(grepl("4-6-4", dfList[[i]]$Image)),]$condition <- "KO_pts"
  dfList[[i]][which(grepl("8-5-6", dfList[[i]]$Image)),]$condition <- "KO_pts"
  
  #make condition a factor so that it always plots in WT then KO order
  dfList[[i]]$condition <- factor(dfList[[i]]$condition, levels = c("WT_sham", "WT_pts", "KO_sham", "KO_pts"))
  
  dfList[[i]][which(grepl("CONTRA", dfList[[i]]$Image)),]$side <- "CONTRA"
  dfList[[i]][which(grepl("IPSI", dfList[[i]]$Image)),]$side <- "IPSI"
  dfList[[i]][which(grepl("IPS", dfList[[i]]$Image)),]$side <- "IPSI"
  
  dfList[[i]]$side <- factor(dfList[[i]]$side, levels = c("IPSI", "CONTRA"))
  
  dfList[[i]]$image_id <- seq.int(nrow(dfList[[i]]))
}

manual_synbot_data <- dfList[[1]]
ilastik_data <- dfList[[2]]
puncta_analyzer_data <- dfList[[3]]
synquant_data <- dfList[[4]]

#remove contralateral data
manual_synbot_contra_data <- filter(manual_synbot_data, side == "CONTRA")
manual_synbot_data <- filter(manual_synbot_data, side == "IPSI")

ilastik_contra_data <- filter(ilastik_data, side == "CONTRA")
ilastik_data <- filter(ilastik_data, side == "IPSI")

puncta_analyzer_contra_data <- filter(puncta_analyzer_data, side == "CONTRA")
puncta_analyzer_data <- filter(puncta_analyzer_data, side == "IPSI")

synquant_contra_data <- filter(synquant_data, side == "CONTRA")
synquant_data <- filter(synquant_data, side == "IPSI")

```

```{r calculate animal means}

dfList <- list(manual_synbot_data, ilastik_data, puncta_analyzer_data, synquant_data)
dfMeansList <- list(data.frame(), data.frame(), data.frame(), data.frame())

for(i in 1:length(dfList)){
  
  dfMeansList[[i]] <- summarize(group_by(dfList[[i]], condition, animal), mean(Colocalized.Puncta.Count))
  
}

manual_raw_means <- dfMeansList[[1]]
ilastik_raw_means <- dfMeansList[[2]]
puncta_analyzer_raw_means <- dfMeansList[[3]]
synquant_raw_means <- dfMeansList[[4]]
  
```

```{r raw data plots}

ggplot() + geom_point(data = manual_raw_means, aes(x = condition, y = `mean(Colocalized.Puncta.Count)`))

ggplot() + geom_point(data = synquant_raw_means, aes(x = condition, y = `mean(Colocalized.Puncta.Count)`))
```


```{r normalize data}

#normalize count by pair
manual_synbot_data$normalized_count <- 0

manual_synbot_data[which(grepl(1, manual_synbot_data$pair)),]$normalized_count <- manual_synbot_data$Colocalized.Puncta.Count[which(grepl(1, manual_synbot_data$pair))]/manual_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(1, manual_raw_means$pair) & grepl("WT_sham", manual_raw_means$condition))]

manual_synbot_data[which(grepl(2, manual_synbot_data$pair)),]$normalized_count <- manual_synbot_data$Colocalized.Puncta.Count[which(grepl(2, manual_synbot_data$pair))]/manual_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(2, manual_raw_means$pair) & grepl("WT_sham", manual_raw_means$condition))]

manual_synbot_data[which(grepl(3, manual_synbot_data$pair)),]$normalized_count <- manual_synbot_data$Colocalized.Puncta.Count[which(grepl(3, manual_synbot_data$pair))]/manual_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(3, manual_raw_means$pair) & grepl("WT_sham", manual_raw_means$condition))]


#normalize count by pair
ilastik_data$normalized_count <- 0

ilastik_data[which(grepl(1, ilastik_data$pair)),]$normalized_count <- ilastik_data$Colocalized.Puncta.Count[which(grepl(1, ilastik_data$pair))]/ilastik_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(1, manual_raw_means$pair) & grepl("WT_sham", ilastik_raw_means$condition))]

ilastik_data[which(grepl(2, ilastik_data$pair)),]$normalized_count <- ilastik_data$Colocalized.Puncta.Count[which(grepl(2, ilastik_data$pair))]/ilastik_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(2, ilastik_raw_means$pair) & grepl("WT_sham", ilastik_raw_means$condition))]

ilastik_data[which(grepl(3, ilastik_data$pair)),]$normalized_count <- ilastik_data$Colocalized.Puncta.Count[which(grepl(3, ilastik_data$pair))]/ilastik_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(3, ilastik_raw_means$pair) & grepl("WT_sham", ilastik_raw_means$condition))]

#normalize count by pair
puncta_analyzer_data$normalized_count <- 0

puncta_analyzer_data[which(grepl(1, puncta_analyzer_data$pair)),]$normalized_count <- puncta_analyzer_data$Colocalized.Puncta.Count[which(grepl(1, puncta_analyzer_data$pair))]/puncta_analyzer_means$`mean(Colocalized.Puncta.Count)`[which(grepl(1, manual_raw_means$pair) & grepl("WT_sham", puncta_analyzer_means$condition))]

puncta_analyzer_data[which(grepl(2, puncta_analyzer_data$pair)),]$normalized_count <- puncta_analyzer_data$Colocalized.Puncta.Count[which(grepl(2, puncta_analyzer_data$pair))]/puncta_analyzer_means$`mean(Colocalized.Puncta.Count)`[which(grepl(2, puncta_analyzer_means$pair) & grepl("WT_sham", puncta_analyzer_means$condition))]

puncta_analyzer_data[which(grepl(3, puncta_analyzer_data$pair)),]$normalized_count <- puncta_analyzer_data$Colocalized.Puncta.Count[which(grepl(3, puncta_analyzer_data$pair))]/puncta_analyzer_means$`mean(Colocalized.Puncta.Count)`[which(grepl(3, puncta_analyzer_means$pair) & grepl("WT_sham", puncta_analyzer_means$condition))]

#normalize count by pair
synquant_data$normalized_count <- 0

synquant_data[which(grepl(1, synquant_data$pair)),]$normalized_count <- synquant_data$Colocalized.Puncta.Count[which(grepl(1, synquant_data$pair))]/synquant_means$`mean(Colocalized.Puncta.Count)`[which(grepl(1, manual_raw_means$pair) & grepl("WT_sham", synquant_means$condition))]

synquant_data[which(grepl(2, synquant_data$pair)),]$normalized_count <- synquant_data$Colocalized.Puncta.Count[which(grepl(2, synquant_data$pair))]/synquant_means$`mean(Colocalized.Puncta.Count)`[which(grepl(2, synquant_means$pair) & grepl("WT_sham", synquant_means$condition))]

synquant_data[which(grepl(3, synquant_data$pair)),]$normalized_count <- synquant_data$Colocalized.Puncta.Count[which(grepl(3, synquant_data$pair))]/synquant_means$`mean(Colocalized.Puncta.Count)`[which(grepl(3, synquant_means$pair) & grepl("WT_sham", synquant_means$condition))]


```




```{r stats}

t.test(`mean(Colocalized.Puncta.Count)` ~ condition, manual_raw_means)

t.test(`mean(Colocalized.Puncta.Count)` ~ condition, ilastik_raw_means)

t.test(`mean(Colocalized.Puncta.Count)` ~ condition, puncta_analyzer_means)

t.test(`mean(Colocalized.Puncta.Count)` ~ condition, synquant_means)

manual_synbot_grouped <- nlme::groupedData(Colocalized.Puncta.Count ~ condition | pair, data = manual_synbot_data)

manual_synbot_lme <- nlme::lme(manual_synbot_grouped)

#manual_synbot_lme
#summary(manual_synbot_lme)
#anova(manual_synbot_lme)

manual_synbot_tukeys <- summary(glht(manual_synbot_lme, linfct=mcp(condition="Tukey")))
#manual_synbot_tukeys
manual_synbot_tukeysPH <- data.frame(as.character(row.names(manual_synbot_tukeys$linfct)), manual_synbot_tukeys$test$pvalues)

manual_p_value <- manual_synbot_tukeysPH$manual_synbot_tukeys.test.pvalues[1]
print(paste("manual p value: ", manual_p_value))

ilastik_grouped <- nlme::groupedData(Colocalized.Puncta.Count ~ condition | pair, data = ilastik_data)

ilastik_lme <- nlme::lme(ilastik_grouped)

#ilastik_lme
#summary(ilastik_lme)
#anova(ilastik_lme)

ilastik_tukeys <- summary(glht(ilastik_lme, linfct=mcp(condition="Tukey")))
#ilastik_tukeys
ilastik_tukeysPH <- data.frame(as.character(row.names(ilastik_tukeys$linfct)), ilastik_tukeys$test$pvalues)

ilastik_p_value <- ilastik_tukeysPH$ilastik_tukeys.test.pvalues[1]
print(paste("ilastik p value: ", ilastik_p_value))

puncta_analyzer_grouped <- nlme::groupedData(Colocalized.Puncta.Count ~ condition | pair, data = puncta_analyzer_data)

puncta_analyzer_lme <- nlme::lme(puncta_analyzer_grouped)

# puncta_analyzer_lme
# summary(puncta_analyzer_lme)
# anova(puncta_analyzer_lme)

puncta_analyzer_tukeys <- summary(glht(puncta_analyzer_lme, linfct=mcp(condition="Tukey")))
# puncta_analyzer_tukeys
puncta_analyzer_tukeysPH <- data.frame(as.character(row.names(puncta_analyzer_tukeys$linfct)), puncta_analyzer_tukeys$test$pvalues)

puncta_analyzer_p_value <- puncta_analyzer_tukeysPH$puncta_analyzer_tukeys.test.pvalues[1]
print(paste("puncta_analyzer p value: ", puncta_analyzer_p_value))


synquant_grouped <- nlme::groupedData(Colocalized.Puncta.Count ~ condition | pair, data = synquant_data)

synquant_lme <- nlme::lme(synquant_grouped)

# synquant_lme
# summary(synquant_lme)
# anova(synquant_lme)

synquant_tukeys <- summary(glht(synquant_lme, linfct=mcp(condition="Tukey")))
# synquant_tukeys
synquant_tukeysPH <- data.frame(as.character(row.names(synquant_tukeys$linfct)), synquant_tukeys$test$pvalues)

synquant_p_value <- synquant_tukeysPH$synquant_tukeys.test.pvalues[1]
print(paste("synquant p value: ", synquant_p_value))

```



```{r plot synapse counts}

ggplot(summarize(group_by(manual_synbot_data, condition), mean(Colocalized.Puncta.Count)), aes(x = condition, y = `mean(Colocalized.Puncta.Count)`)) + 
  geom_col(fill = NA, color = "black") + 
  geom_jitter(data = manual_synbot_data, aes(x = condition, y = Colocalized.Puncta.Count)) +
  labs(title = "Chrdl1 KO Synapses Manual SynBot", y = "Colocalized Puncta per Image") 
#+ annotate("text", x = 2, y = 2750, label = "p<0.001")

#ggsave("invivo_a2d1_manual.pdf", width = 3.5, height = 5)

ggplot(summarize(group_by(ilastik_data, condition), mean(Colocalized.Puncta.Count)), aes(x = condition, y = `mean(Colocalized.Puncta.Count)`)) + 
  geom_col(fill = NA, color = "black") +
  geom_jitter(data = ilastik_data, aes(x = condition, y = Colocalized.Puncta.Count)) +
  labs(title = "in vivo Synapses ilastik SynBot", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 3250, label = "p=0.003")

#ggsave("invivo_a2d1_ilastik.pdf", width = 3.5, height = 5)

ggplot(summarize(group_by(puncta_analyzer_data, condition), mean(Colocalized.Puncta.Count)), aes(x = condition, y = `mean(Colocalized.Puncta.Count)`)) + 
  geom_col(fill = NA, color = "black") +
  geom_jitter(data = puncta_analyzer_data, aes(x = condition, y = Colocalized.Puncta.Count)) +
  labs(title = "in vivo Synapses Puncta Analyzer", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 800, label = "p=0.007")

#ggsave("invivo_a2d1_puncta_analyzer.pdf", width = 3.5, height = 5)

ggplot(summarize(group_by(synquant_data, condition), mean(Colocalized.Puncta.Count)), aes(x = condition, y = `mean(Colocalized.Puncta.Count)`)) + 
  geom_col(fill = NA, color = "black") +
  geom_jitter(data = synquant_data, aes(x = condition, y = Colocalized.Puncta.Count)) +
  labs(title = "in vivo Synapses SynQuant", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 3000, label = "p<0.001")

#ggsave("invivo_a2d1_synquant.pdf", width = 3.5, height = 5)

```



```{r normalized stats}

#calculate normalized condition means for each pair
manual_norm_means <- summarize(group_by(manual_synbot_data, condition, pair), mean(normalized_count))

ilastik_norm_means <- summarize(group_by(ilastik_data, condition, pair), mean(normalized_count))

puncta_analyzer_norm_means <- summarize(group_by(puncta_analyzer_data, condition, pair), mean(normalized_count))

synquant_norm_means <- summarize(group_by(synquant_data, condition, pair), mean(normalized_count))


manual_synbot_grouped <- nlme::groupedData(normalized_count ~ condition | pair, data = manual_synbot_data)

manual_synbot_lme <- nlme::lme(manual_synbot_grouped)

manual_synbot_lme
summary(manual_synbot_lme)
anova(manual_synbot_lme)

manual_synbot_tukeys <- summary(glht(manual_synbot_lme, linfct=mcp(condition="Tukey")))
manual_synbot_tukeys
manual_synbot_tukeysPH <- data.frame(as.character(row.names(manual_synbot_tukeys$linfct)), manual_synbot_tukeys$test$pvalues)

#calculate sem = sd/sqrt(n)
manual_sem_wt <- sd(manual_norm_means$`mean(normalized_count)`[which(grepl("WT", manual_norm_means$condition))])/sqrt(length(manual_norm_means$condition[which(grepl("WT", manual_norm_means$condition))]))

manual_sem_ko <- sd(manual_norm_means$`mean(normalized_count)`[which(grepl("KO", manual_norm_means$condition))])/sqrt(length(manual_norm_means$condition[which(grepl("KO", manual_norm_means$condition))]))

manual_synbot_data$sem <- 0
manual_synbot_data$sem[which(grepl("WT", manual_synbot_data$condition))] <- manual_sem_wt
manual_synbot_data$sem[which(grepl("KO", manual_synbot_data$condition))] <- manual_sem_ko

#add normalized count to data frame
manual_synbot_data$mean_normalized_count <- 0
manual_synbot_data$mean_normalized_count[which(grepl("WT", manual_synbot_data$condition))] <- mean(manual_synbot_data$normalized_count[which(grepl("WT", manual_synbot_data$condition))])
manual_synbot_data$mean_normalized_count[which(grepl("KO", manual_synbot_data$condition))] <- mean(manual_synbot_data$normalized_count[which(grepl("KO", manual_synbot_data$condition))])



ilastik_grouped <- nlme::groupedData(normalized_count ~ condition | pair, data = ilastik_data)

ilastik_lme <- nlme::lme(ilastik_grouped)

ilastik_lme
summary(ilastik_lme)
anova(ilastik_lme)

ilastik_tukeys <- summary(glht(ilastik_lme, linfct=mcp(condition="Tukey")))
ilastik_tukeys
ilastik_tukeysPH <- data.frame(as.character(row.names(ilastik_tukeys$linfct)), ilastik_tukeys$test$pvalues)

#calculate sem = sd/sqrt(n)
ilastik_sem_wt <- sd(ilastik_norm_means$`mean(normalized_count)`[which(grepl("WT", ilastik_norm_means$condition))])/sqrt(length(ilastik_norm_means$condition[which(grepl("WT", ilastik_norm_means$condition))]))

ilastik_sem_ko <- sd(ilastik_norm_means$`mean(normalized_count)`[which(grepl("KO", ilastik_norm_means$condition))])/sqrt(length(ilastik_norm_means$condition[which(grepl("KO", ilastik_norm_means$condition))]))

ilastik_data$sem <- 0
ilastik_data$sem[which(grepl("WT", ilastik_data$condition))] <- ilastik_sem_wt
ilastik_data$sem[which(grepl("KO", ilastik_data$condition))] <- ilastik_sem_ko

#add normalized count to data frame
ilastik_data$mean_normalized_count <- 0
ilastik_data$mean_normalized_count[which(grepl("WT", ilastik_data$condition))] <- mean(ilastik_data$normalized_count[which(grepl("WT", ilastik_data$condition))])
ilastik_data$mean_normalized_count[which(grepl("KO", ilastik_data$condition))] <- mean(ilastik_data$normalized_count[which(grepl("KO", ilastik_data$condition))])


puncta_analyzer_grouped <- nlme::groupedData(normalized_count ~ condition | pair, data = puncta_analyzer_data)

puncta_analyzer_lme <- nlme::lme(puncta_analyzer_grouped)

puncta_analyzer_lme
summary(puncta_analyzer_lme)
anova(puncta_analyzer_lme)

puncta_analyzer_tukeys <- summary(glht(puncta_analyzer_lme, linfct=mcp(condition="Tukey")))
puncta_analyzer_tukeys
puncta_analyzer_tukeysPH <- data.frame(as.character(row.names(puncta_analyzer_tukeys$linfct)), puncta_analyzer_tukeys$test$pvalues)

#calculate sem = sd/sqrt(n)
puncta_analyzer_sem_wt <- sd(puncta_analyzer_norm_means$`mean(normalized_count)`[which(grepl("WT", puncta_analyzer_norm_means$condition))])/sqrt(length(puncta_analyzer_norm_means$condition[which(grepl("WT", puncta_analyzer_norm_means$condition))]))

puncta_analyzer_sem_ko <- sd(puncta_analyzer_norm_means$`mean(normalized_count)`[which(grepl("KO", puncta_analyzer_norm_means$condition))])/sqrt(length(puncta_analyzer_norm_means$condition[which(grepl("KO", puncta_analyzer_norm_means$condition))]))

puncta_analyzer_data$sem <- 0
puncta_analyzer_data$sem[which(grepl("WT", puncta_analyzer_data$condition))] <- puncta_analyzer_sem_wt
puncta_analyzer_data$sem[which(grepl("KO", puncta_analyzer_data$condition))] <- puncta_analyzer_sem_ko

#add normalized count to data frame
puncta_analyzer_data$mean_normalized_count <- 0
puncta_analyzer_data$mean_normalized_count[which(grepl("WT", puncta_analyzer_data$condition))] <- mean(puncta_analyzer_data$normalized_count[which(grepl("WT", puncta_analyzer_data$condition))])
puncta_analyzer_data$mean_normalized_count[which(grepl("KO", puncta_analyzer_data$condition))] <- mean(puncta_analyzer_data$normalized_count[which(grepl("KO", puncta_analyzer_data$condition))])


synquant_grouped <- nlme::groupedData(normalized_count ~ condition | pair, data = synquant_data)

synquant_lme <- nlme::lme(synquant_grouped)

synquant_lme
summary(synquant_lme)
anova(synquant_lme)

synquant_tukeys <- summary(glht(synquant_lme, linfct=mcp(condition="Tukey")))
synquant_tukeys
synquant_tukeysPH <- data.frame(as.character(row.names(synquant_tukeys$linfct)), synquant_tukeys$test$pvalues)

#calculate sem = sd/sqrt(n)
synquant_sem_wt <- sd(synquant_norm_means$`mean(normalized_count)`[which(grepl("WT", synquant_norm_means$condition))])/sqrt(length(synquant_norm_means$condition[which(grepl("WT", synquant_norm_means$condition))]))

synquant_sem_ko <- sd(synquant_norm_means$`mean(normalized_count)`[which(grepl("KO", synquant_norm_means$condition))])/sqrt(length(synquant_norm_means$condition[which(grepl("KO", synquant_norm_means$condition))]))

synquant_data$sem <- 0
synquant_data$sem[which(grepl("WT", synquant_data$condition))] <- synquant_sem_wt
synquant_data$sem[which(grepl("KO", synquant_data$condition))] <- synquant_sem_ko

#add normalized count to data frame
synquant_data$mean_normalized_count <- 0
synquant_data$mean_normalized_count[which(grepl("WT", synquant_data$condition))] <- mean(synquant_data$normalized_count[which(grepl("WT", synquant_data$condition))])
synquant_data$mean_normalized_count[which(grepl("KO", synquant_data$condition))] <- mean(synquant_data$normalized_count[which(grepl("KO", synquant_data$condition))])

```

```{r plot normalized synapse counts}

manual_plot.df <- summarize(group_by(manual_synbot_data, condition), mean(normalized_count))
manual_plot.df$sem <- 0
manual_plot.df$sem[which(grepl("WT", manual_plot.df$condition))] <- manual_sem_wt
manual_plot.df$sem[which(grepl("KO", manual_plot.df$condition))] <- manual_sem_ko

ggplot(manual_plot.df, aes(x = condition, y = `mean(normalized_count)`)) + 
  geom_col(fill = NA, color = "black") + 
  geom_jitter(data = manual_synbot_data, aes(x = condition, y = normalized_count), color = "darkgray") +
  geom_point(data = manual_norm_means, aes(x = condition, y = `mean(normalized_count)`), size = 5, position = position_dodge2(0.5)) +
  labs(title = "in vivo Synapses Manual SynBot", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 1.3, label = "p<0.001") +
  geom_errorbar(aes(ymin=`mean(normalized_count)`-sem, ymax=`mean(normalized_count)`+sem), width=.2)

#ggsave("invivo_a2d1_manual.pdf", width = 3.5, height = 5)

ilastik_plot.df <- summarize(group_by(ilastik_data, condition), mean(normalized_count))
ilastik_plot.df$sem <- 0
ilastik_plot.df$sem[which(grepl("WT", ilastik_plot.df$condition))] <- ilastik_sem_wt
ilastik_plot.df$sem[which(grepl("KO", ilastik_plot.df$condition))] <- ilastik_sem_ko

ggplot(ilastik_plot.df, aes(x = condition, y = `mean(normalized_count)`)) + 
  geom_col(fill = NA, color = "black") +
  geom_jitter(data = ilastik_data, aes(x = condition, y = normalized_count), color = "darkgray") +
  geom_point(data = ilastik_norm_means, aes(x = condition, y = `mean(normalized_count)`), size = 5, position = position_dodge2(0.5)) +
  labs(title = "in vivo Synapses ilastik SynBot", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 1.5, label = "p=0.002") +
  geom_errorbar(aes(ymin=`mean(normalized_count)`-sem, ymax=`mean(normalized_count)`+sem), width=.2,
                 position=position_dodge(.9))

#ggsave("invivo_a2d1_ilastik.pdf", width = 3.5, height = 5)

puncta_analyzer_plot.df <- summarize(group_by(puncta_analyzer_data, condition), mean(normalized_count))
puncta_analyzer_plot.df$sem <- 0
puncta_analyzer_plot.df$sem[which(grepl("WT", puncta_analyzer_plot.df$condition))] <- puncta_analyzer_sem_wt
puncta_analyzer_plot.df$sem[which(grepl("KO", puncta_analyzer_plot.df$condition))] <- puncta_analyzer_sem_ko

ggplot(puncta_analyzer_plot.df, aes(x = condition, y = `mean(normalized_count)`)) + 
  geom_col(fill = NA, color = "black") +
  geom_jitter(data = puncta_analyzer_data, aes(x = condition, y = normalized_count), color = "darkgray") +
  geom_point(data = puncta_analyzer_norm_means, aes(x = condition, y = `mean(normalized_count)`), size = 5, position = position_dodge2(0.5)) +
  labs(title = "in vivo Synapses Puncta Analyzer", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 1.5, label = "p<0.001") +
  geom_errorbar(aes(ymin=`mean(normalized_count)`-sem, ymax=`mean(normalized_count)`+sem), width=.2,
                 position=position_dodge(.9))

#ggsave("invivo_a2d1_puncta_analyzer.pdf", width = 3.5, height = 5)

synquant_plot.df <- summarize(group_by(synquant_data, condition), mean(normalized_count))
synquant_plot.df$sem <- 0
synquant_plot.df$sem[which(grepl("WT", synquant_plot.df$condition))] <- synquant_sem_wt
synquant_plot.df$sem[which(grepl("KO", synquant_plot.df$condition))] <- synquant_sem_ko

ggplot(synquant_plot.df, aes(x = condition, y = `mean(normalized_count)`)) + 
  geom_col(fill = NA, color = "black") +
  geom_jitter(data = synquant_data, aes(x = condition, y = normalized_count), color = "darkgray") +
  geom_point(data = synquant_norm_means, aes(x = condition, y = `mean(normalized_count)`), size = 5, position = position_dodge2(0.5)) +
  labs(title = "in vivo Synapses Puncta Analyzer", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 1.5, label = "p<0.001") +
  geom_errorbar(aes(ymin=`mean(normalized_count)`-sem, ymax=`mean(normalized_count)`+sem), width=.2,
                 position=position_dodge(.9))

#ggsave("invivo_a2d1_synquant.pdf", width = 3.5, height = 5)

```

```{r faceted plots}

#combine data into one data frame

combined_data <- rbind(manual_synbot_data, ilastik_data)

combined_data <- rbind(combined_data, puncta_analyzer_data)

combined_data <- rbind(combined_data, synquant_data)

ggplot(data= combined_data, aes(x=condition, y=normalized_count)) + 
  geom_bar(stat = "summary", fill = NA, color = "black") +
  facet_grid(cols = vars(analysis_type)) +
  geom_jitter(size = 0.5, width = 0.1, aes(color = condition)) +
  geom_point(data = summarize(group_by(combined_data, analysis_type, condition, pair), mean(normalized_count)), aes(x = condition, y = `mean(normalized_count)`, color = condition), size = 3, position = position_dodge2(0.5)) +
  geom_errorbar(aes(ymin=mean_normalized_count-sem, ymax=mean_normalized_count+sem), width=.2,
                 position=position_dodge(.9)) +
  labs(y = "Fold change in synapse number \n (colocalization of VGluT1 and PSD95)") +
  scale_color_manual(values = c("black", "black")) + theme(legend.position = "none")

#ggsave("F:/Savage_Dropbox/Duke Research Team Dropbox/Justin Savage/Team_Syn_Bot/20240116_figures/figure_5_in_vivo/invivo_a2d1_faceted.pdf", width = 6.5, height = 3.5)

```

```{r simple lm }

model_1 <- aov(normalized_count~analysis_typecondition, data = combined_data)
summary(model_1)

tukey_1 <- TukeyHSD(model_1)
tukey_1
```

```{r repeated measures plot}

gg.base <- ggplot(combined_data, aes(x = analysis_type, y = Red.Puncta.Count))
gg.base + geom_line(aes(group = image_id, linetype = condition)) + geom_point(aes(group = image_id, shape = condition)) + stat_summary(mapping = aes(x = analysis_type, y = Red.Puncta.Count), fill = NA , geom = 'col', fun.y = 'mean', color = 'black') + scale_color_viridis_b() + facet_grid(cols = vars(condition))+ scale_x_discrete(labels=c('puncta \n analyzer', 'manual \n synbot', 'ilastik')) + ylab("PSD95 (Red) Puncta Count")

#ggsave("F:/Savage_Dropbox/Dropbox (Duke Research Team)/Team_Syn_Bot/20230103_figures/figure_s1_line_plots/invivo_red_line_plot_raw.pdf", width = 5, height = 2.75)

gg.base <- ggplot(combined_data, aes(x = analysis_type, y = Green.Puncta.Count))
gg.base + geom_line(aes(group = image_id, linetype = condition)) + geom_point(aes(group = image_id, shape = condition)) + stat_summary(mapping = aes(x = analysis_type, y = Green.Puncta.Count), fill = NA , geom = 'col', fun.y = 'mean', color = 'black') + scale_color_viridis_b() + facet_grid(cols = vars(condition))+ scale_x_discrete(labels=c('puncta \n analyzer', 'manual \n synbot', 'ilastik')) + ylab("VGLuT1 (Green) Puncta Count")

#ggsave("F:/Savage_Dropbox/Dropbox (Duke Research Team)/Team_Syn_Bot/20230103_figures/figure_s1_line_plots/invivo_green_line_plot_raw.pdf", width = 5, height = 2.75)

gg.base <- ggplot(combined_data, aes(x = analysis_type, y = Colocalized.Puncta.Count))
gg.base + geom_line(aes(group = image_id, linetype = condition)) + geom_point(aes(group = image_id, shape = condition)) + stat_summary(mapping = aes(x = analysis_type, y = Colocalized.Puncta.Count), fill = NA , geom = 'col', fun.y = 'mean', color = 'black') + scale_color_viridis_b() + facet_grid(cols = vars(condition))+ scale_x_discrete(labels=c('puncta \n analyzer', 'manual \n synbot', 'ilastik')) + ylab("Colocalized Puncta Count")

#ggsave("F:/Savage_Dropbox/Dropbox (Duke Research Team)/Team_Syn_Bot/20230103_figures/figure_s1_line_plots/invivo_coloc_line_plot_raw.pdf", width = 5, height = 2.75)


```






```{r test for difference in analysis methods}

model_1 <- aov(normalized_count~analysis_type+condition, data = combined_data)
summary(model_1)

tukey_1 <- TukeyHSD(model_1)
tukey_1

combined_data_grouped <- nlme::groupedData(normalized_count ~ analysis_type | condition, data = combined_data)

combined_data_lme <- nlme::lme(combined_data_grouped)

combined_data_lme
summary(combined_data_lme)
anova(combined_data_lme)

```





```{r session info}
sessionInfo()

```



