---
title: "20240116_invivo_a2d1_plots"
output: html_document
date: "2024-01-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(tidyverse)
library(ggplot2)
library(agricolae)
library(ggsignif)
library(multcomp)
library(nlme)
```


```{r load data}



manual_synbot_circle <- read.csv("circle_v_pixel/Summary_circle.csv")
manual_synbot_pixel <- read.csv("circle_v_pixel/Summary_pixel.csv")


#label data with the analysis type used
manual_synbot_circle$analysis_type <- "manual_synbot_circle"
manual_synbot_pixel$analysis_type <- "manual_synbot_pixel"

#make analysis_type a factor so that it always plots in puncta_analyzer, manual, ilastik order
manual_synbot_circle$analysis_type <- factor(manual_synbot_circle$analysis_type, levels = c("manual_synbot_circle", "manual_synbot_pixel"))

#initialize condition
manual_synbot_circle$condition <- "WT"
manual_synbot_pixel$condition <- "WT"

#label data with experimental condition
manual_synbot_circle[which(grepl("*WT*", manual_synbot_circle$Image)),]$condition <- "WT"
manual_synbot_circle[which(grepl("*KO*", manual_synbot_circle$Image)),]$condition <- "KO"

#make condition a factor so that it always plots in WT then KO order
manual_synbot_circle$condition <- factor(manual_synbot_circle$condition, levels = c("WT", "KO"))

manual_synbot_pixel[which(grepl("*WT*", manual_synbot_pixel$Image)),]$condition <- "WT"
manual_synbot_pixel[which(grepl("*KO*", manual_synbot_pixel$Image)),]$condition <- "KO"

manual_synbot_pixel$condition <- factor(manual_synbot_pixel$condition, levels = c("WT", "KO"))


#TODO: Make sure this is numbering correctly
#add image_id
manual_synbot_pixel$image_id <- seq.int(nrow(manual_synbot_pixel))
manual_synbot_circle$image_id <- seq.int(nrow(manual_synbot_circle))


#initialize pair
manual_synbot_circle$pair <- 1
manual_synbot_pixel$pair <- 1
#add pair number
manual_synbot_circle[which(grepl("Pair1", manual_synbot_circle$Image)),]$pair <- 1
manual_synbot_circle[which(grepl("Pair2", manual_synbot_circle$Image)),]$pair <- 2
manual_synbot_circle[which(grepl("Pair3", manual_synbot_circle$Image)),]$pair <- 3

manual_synbot_pixel[which(grepl("Pair1", manual_synbot_pixel$Image)),]$pair <- 1
manual_synbot_pixel[which(grepl("Pair2", manual_synbot_pixel$Image)),]$pair <- 2
manual_synbot_pixel[which(grepl("Pair3", manual_synbot_pixel$Image)),]$pair <- 3


#calculate condition means for each pair
manual_circle_raw_means <- summarize(group_by(manual_synbot_circle, condition, pair), mean(Colocalized.Puncta.Count))

manual_pixel_raw_means <- summarize(group_by(manual_synbot_pixel, condition, pair), mean(Colocalized.Puncta.Count))


#normalize count by pair
manual_synbot_circle$normalized_count <- 0

manual_synbot_circle[which(grepl(1, manual_synbot_circle$pair)),]$normalized_count <- manual_synbot_circle$Colocalized.Puncta.Count[which(grepl(1, manual_synbot_circle$pair))]/manual_circle_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(1, manual_circle_raw_means$pair) & grepl("WT", manual_circle_raw_means$condition))]

manual_synbot_circle[which(grepl(2, manual_synbot_circle$pair)),]$normalized_count <- manual_synbot_circle$Colocalized.Puncta.Count[which(grepl(2, manual_synbot_circle$pair))]/manual_circle_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(2, manual_circle_raw_means$pair) & grepl("WT", manual_circle_raw_means$condition))]

manual_synbot_circle[which(grepl(3, manual_synbot_circle$pair)),]$normalized_count <- manual_synbot_circle$Colocalized.Puncta.Count[which(grepl(3, manual_synbot_circle$pair))]/manual_circle_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(3, manual_circle_raw_means$pair) & grepl("WT", manual_circle_raw_means$condition))]


#normalize count by pair
manual_synbot_pixel$normalized_count <- 0

manual_synbot_pixel[which(grepl(1, manual_synbot_pixel$pair)),]$normalized_count <- manual_synbot_pixel$Colocalized.Puncta.Count[which(grepl(1, manual_synbot_pixel$pair))]/manual_pixel_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(1, manual_circle_raw_means$pair) & grepl("WT", manual_pixel_raw_means$condition))]

manual_synbot_pixel[which(grepl(2, manual_synbot_pixel$pair)),]$normalized_count <- manual_synbot_pixel$Colocalized.Puncta.Count[which(grepl(2, manual_synbot_pixel$pair))]/manual_pixel_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(2, manual_pixel_raw_means$pair) & grepl("WT", manual_pixel_raw_means$condition))]

manual_synbot_pixel[which(grepl(3, manual_synbot_pixel$pair)),]$normalized_count <- manual_synbot_pixel$Colocalized.Puncta.Count[which(grepl(3, manual_synbot_pixel$pair))]/manual_pixel_raw_means$`mean(Colocalized.Puncta.Count)`[which(grepl(3, manual_pixel_raw_means$pair) & grepl("WT", manual_pixel_raw_means$condition))]

```




```{r stats}

t.test(`mean(Colocalized.Puncta.Count)` ~ condition, manual_circle_raw_means)

t.test(`mean(Colocalized.Puncta.Count)` ~ condition, manual_pixel_raw_means)

manual_synbot_circle_grouped <- nlme::groupedData(Colocalized.Puncta.Count ~ condition | pair, data = manual_synbot_circle)

manual_synbot_circle_lme <- nlme::lme(manual_synbot_circle_grouped)

#manual_synbot_circle_lme
#summary(manual_synbot_circle_lme)
#anova(manual_synbot_circle_lme)

manual_synbot_circle_tukeys <- summary(glht(manual_synbot_circle_lme, linfct=mcp(condition="Tukey")))
#manual_synbot_circle_tukeys
manual_synbot_circle_tukeysPH <- data.frame(as.character(row.names(manual_synbot_circle_tukeys$linfct)), manual_synbot_circle_tukeys$test$pvalues)

manual_circle_p_value <- manual_synbot_circle_tukeysPH$manual_synbot_circle_tukeys.test.pvalues[1]
print(paste("manual circle p value: ", manual_circle_p_value))



manual_synbot_pixel_grouped <- nlme::groupedData(Colocalized.Puncta.Count ~ condition | pair, data = manual_synbot_pixel)

manual_synbot_pixel_lme <- nlme::lme(manual_synbot_pixel_grouped)

#manual_synbot_pixel_lme
#summary(manual_synbot_pixel_lme)
#anova(manual_synbot_pixel_lme)

manual_synbot_pixel_tukeys <- summary(glht(manual_synbot_pixel_lme, linfct=mcp(condition="Tukey")))
#manual_synbot_pixel_tukeys
manual_synbot_pixel_tukeysPH <- data.frame(as.character(row.names(manual_synbot_pixel_tukeys$linfct)), manual_synbot_pixel_tukeys$test$pvalues)

manual_pixel_p_value <- manual_synbot_pixel_tukeysPH$manual_synbot_pixel_tukeys.test.pvalues[1]
print(paste("manual pixel p value: ", manual_pixel_p_value))



```

```{r plot synapse counts}

ggplot(summarize(group_by(manual_synbot_circle, condition), mean(Colocalized.Puncta.Count)), aes(x = condition, y = `mean(Colocalized.Puncta.Count)`)) + 
  geom_col(fill = NA, color = "black") + 
  geom_jitter(data = manual_synbot_circle, aes(x = condition, y = Colocalized.Puncta.Count)) +
  labs(title = "in vivo Synapses Manual SynBot Circle", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 2750)

#ggsave("invivo_a2d1_manual.pdf", width = 3.5, height = 5)


ggplot(summarize(group_by(manual_synbot_pixel, condition), mean(Colocalized.Puncta.Count)), aes(x = condition, y = `mean(Colocalized.Puncta.Count)`)) + 
  geom_col(fill = NA, color = "black") +
  geom_jitter(data = manual_synbot_pixel, aes(x = condition, y = Colocalized.Puncta.Count)) +
  labs(title = "in vivo Synapses Manual SynBot Pixel", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 800)

#ggsave("invivo_a2d1_puncta_analyzer.pdf", width = 3.5, height = 5)


```



```{r normalized stats}

#calculate normalized condition means for each pair
manual_circle_norm_means <- summarize(group_by(manual_synbot_circle, condition, pair), mean(normalized_count))


manual_synbot_circle_grouped <- nlme::groupedData(normalized_count ~ condition | pair, data = manual_synbot_circle)

manual_synbot_circle_lme <- nlme::lme(manual_synbot_circle_grouped)

manual_synbot_circle_lme
summary(manual_synbot_circle_lme)
anova(manual_synbot_circle_lme)

manual_synbot_circle_tukeys <- summary(glht(manual_synbot_circle_lme, linfct=mcp(condition="Tukey")))
manual_synbot_circle_tukeys
manual_synbot_circle_tukeysPH <- data.frame(as.character(row.names(manual_synbot_circle_tukeys$linfct)), manual_synbot_circle_tukeys$test$pvalues)

#calculate sem = sd/sqrt(n)
manual_circle_sem_wt <- sd(manual_circle_norm_means$`mean(normalized_count)`[which(grepl("WT", manual_circle_norm_means$condition))])/sqrt(length(manual_circle_norm_means$condition[which(grepl("WT", manual_circle_norm_means$condition))]))

manual_circle_sem_ko <- sd(manual_circle_norm_means$`mean(normalized_count)`[which(grepl("KO", manual_circle_norm_means$condition))])/sqrt(length(manual_circle_norm_means$condition[which(grepl("KO", manual_circle_norm_means$condition))]))

manual_synbot_circle$sem <- 0
manual_synbot_circle$sem[which(grepl("WT", manual_synbot_circle$condition))] <- manual_circle_sem_wt
manual_synbot_circle$sem[which(grepl("KO", manual_synbot_circle$condition))] <- manual_circle_sem_ko

#add normalized count to data frame
manual_synbot_circle$mean_normalized_count <- 0
manual_synbot_circle$mean_normalized_count[which(grepl("WT", manual_synbot_circle$condition))] <- mean(manual_synbot_circle$normalized_count[which(grepl("WT", manual_synbot_circle$condition))])
manual_synbot_circle$mean_normalized_count[which(grepl("KO", manual_synbot_circle$condition))] <- mean(manual_synbot_circle$normalized_count[which(grepl("KO", manual_synbot_circle$condition))])





#calculate normalized condition means for each pair
manual_pixel_norm_means <- summarize(group_by(manual_synbot_pixel, condition, pair), mean(normalized_count))


manual_synbot_pixel_grouped <- nlme::groupedData(normalized_count ~ condition | pair, data = manual_synbot_pixel)

manual_synbot_pixel_lme <- nlme::lme(manual_synbot_pixel_grouped)

manual_synbot_pixel_lme
summary(manual_synbot_pixel_lme)
anova(manual_synbot_pixel_lme)

manual_synbot_pixel_tukeys <- summary(glht(manual_synbot_pixel_lme, linfct=mcp(condition="Tukey")))
manual_synbot_pixel_tukeys
manual_synbot_pixel_tukeysPH <- data.frame(as.character(row.names(manual_synbot_pixel_tukeys$linfct)), manual_synbot_pixel_tukeys$test$pvalues)

#calculate sem = sd/sqrt(n)
manual_pixel_sem_wt <- sd(manual_pixel_norm_means$`mean(normalized_count)`[which(grepl("WT", manual_pixel_norm_means$condition))])/sqrt(length(manual_pixel_norm_means$condition[which(grepl("WT", manual_pixel_norm_means$condition))]))

manual_pixel_sem_ko <- sd(manual_pixel_norm_means$`mean(normalized_count)`[which(grepl("KO", manual_pixel_norm_means$condition))])/sqrt(length(manual_pixel_norm_means$condition[which(grepl("KO", manual_pixel_norm_means$condition))]))

manual_synbot_pixel$sem <- 0
manual_synbot_pixel$sem[which(grepl("WT", manual_synbot_pixel$condition))] <- manual_pixel_sem_wt
manual_synbot_pixel$sem[which(grepl("KO", manual_synbot_pixel$condition))] <- manual_pixel_sem_ko

#add normalized count to data frame
manual_synbot_pixel$mean_normalized_count <- 0
manual_synbot_pixel$mean_normalized_count[which(grepl("WT", manual_synbot_pixel$condition))] <- mean(manual_synbot_pixel$normalized_count[which(grepl("WT", manual_synbot_pixel$condition))])
manual_synbot_pixel$mean_normalized_count[which(grepl("KO", manual_synbot_pixel$condition))] <- mean(manual_synbot_pixel$normalized_count[which(grepl("KO", manual_synbot_pixel$condition))])


```

```{r plot normalized synapse counts}

manual_circle_plot.df <- summarize(group_by(manual_synbot_circle, condition), mean(normalized_count))
manual_circle_plot.df$sem <- 0
manual_circle_plot.df$sem[which(grepl("WT", manual_circle_plot.df$condition))] <- manual_circle_sem_wt
manual_circle_plot.df$sem[which(grepl("KO", manual_circle_plot.df$condition))] <- manual_circle_sem_ko

ggplot(manual_circle_plot.df, aes(x = condition, y = `mean(normalized_count)`)) + 
  geom_col(fill = NA, color = "black") + 
  geom_jitter(data = manual_synbot_circle, aes(x = condition, y = normalized_count), color = "darkgray") +
  geom_point(data = manual_circle_norm_means, aes(x = condition, y = `mean(normalized_count)`), size = 5, position = position_dodge2(0.5)) +
  labs(title = "in vivo Synapses Manual SynBot circle", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 1.3, label = "p<0.001") +
  geom_errorbar(aes(ymin=`mean(normalized_count)`-sem, ymax=`mean(normalized_count)`+sem), width=.2)

manual_pixel_plot.df <- summarize(group_by(manual_synbot_pixel, condition), mean(normalized_count))
manual_pixel_plot.df$sem <- 0
manual_pixel_plot.df$sem[which(grepl("WT", manual_pixel_plot.df$condition))] <- manual_pixel_sem_wt
manual_pixel_plot.df$sem[which(grepl("KO", manual_pixel_plot.df$condition))] <- manual_pixel_sem_ko

ggplot(manual_pixel_plot.df, aes(x = condition, y = `mean(normalized_count)`)) + 
  geom_col(fill = NA, color = "black") + 
  geom_jitter(data = manual_synbot_pixel, aes(x = condition, y = normalized_count), color = "darkgray") +
  geom_point(data = manual_pixel_norm_means, aes(x = condition, y = `mean(normalized_count)`), size = 5, position = position_dodge2(0.5)) +
  labs(title = "in vivo Synapses Manual SynBot pixel", y = "Colocalized Puncta per Image") +
  annotate("text", x = 2, y = 1.3, label = "p<0.001") +
  geom_errorbar(aes(ymin=`mean(normalized_count)`-sem, ymax=`mean(normalized_count)`+sem), width=.2)


```

```{r faceted plots}

#combine data into one data frame

combined_data <- rbind(manual_synbot_circle, manual_synbot_pixel)

ggplot(data= combined_data, aes(x=condition, y=normalized_count)) + 
  geom_bar(stat = "summary", fill = NA, color = "black") +
  facet_grid(cols = vars(analysis_type)) +
  geom_jitter(size = 0.5, width = 0.1, aes(color = condition)) +
  geom_point(data = summarize(group_by(combined_data, analysis_type, condition, pair), mean(normalized_count)), aes(x = condition, y = `mean(normalized_count)`, color = condition), size = 3, position = position_dodge2(0.5)) +
  geom_errorbar(aes(ymin=mean_normalized_count-sem, ymax=mean_normalized_count+sem), width=.2,
                 position=position_dodge(.9)) +
  labs(y = "Fold change in synapse number \n (colocalization of VGluT1 and PSD95)") +
  scale_color_manual(values = c("black", "black")) + theme(legend.position = "none")


#ggsave("F:/Savage_Dropbox/Duke Research Team Dropbox/Justin Savage/Team_Syn_Bot/20240318_figures/figure_6_in_vivo/20240619_circle_v_pixel.pdf", width = 6.5, height = 3.5)

```






```{r session info}
sessionInfo()

```



